class CarVO:
    DIVAR_CAR_URL = "https://divar.ir/car/prices"
    NAME_CLASS = "kt-price-row__text kt-price-row__title"
    VALUE_CLASS = "kt-price-row__text kt-price-row__value"
    OTHER_CLASS = "kt-price-row__text kt-price-row__subtitle kt-price-row__subtitle--top"
    NAME = "name"
    MODEL_FA_NAME = "model_fa_name"
    PRICE = "price"
    PRODUCTION_YEAR = "production_year"
    DATE = "date"
    BRAND_FA_NAME = "brand_fa_name"
    LAST_UPDATE_DATETIME = "last_update_datetime"
    PUBLISH_DATETIME = "publish_datetime"
    ID = "id"
